---
title: "Enfoque Axiomático"
subtitle: " [XS-0122 Modelos Probabilísticos II Semestre 2025](https://christopher-tr.github.io/XS3310-I25)"
format: clean-revealjs
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"



author:
  - name: Christopher Torres Rojas
    url: https://christopher-tr.github.io/
    email: christopher.torres@ucr.ac.cr
    affiliations: 
    - name: Escuela de Estadística, Universidad de Costa Rica
      url: https://www.estadistica.ucr.ac.cr/
#date: last-modified
lang: es  # español
---

## Axiomas

#### **Definición (Espacio Muestral** $\Omega$**)**

Al conjunto de todos los posibles resultados de un experimento aleatorio, se llama espacio muestral y se denota por $\Omega$

#### **Definición (Espacio Muestral Discreto)**

El espacio muestral $\Omega$ se llama *discreto* si es finito o numerable. Un experimento aleatorio se llama *finito* (discreto) si su espacio muestral es finito (discreto). El espacio muestral se llama *continuo* si es un intervalo.

[Nota: Es importante repasar las propiedades de conjuntos de la primera clase.]{style="font-size:85%;"}

## Axiomas

#### **Definición (Evento Simple)**

Un evento simple es cada uno de los posibles resultados de un experimento aleatorio, es decir, cada uno de los puntos muestrales.

#### **Definición (Evento Compuesto)**

Un evento compuesto es un conjunto de posibles resultados de un experimento aleatorio, es decir, un conjunto de eventos simples, por lo que, es un subconjunto del espacio muestral.

## Axiomas

*Experimento Aleatorio:* Lanzar un dado.

*Espacio Muestral* $\Omega = \{1,2,3,4,5,6\}$

*Evento Simple:* Que salga un 2 $=\{2\}$

*Evento Compuesto:* Que salga un número primo $=\{1,2,3,5\}$

## Axiomas

-   Diremos que ***A es subconjunto de B*** $\left( A \subset B\right)$. Si todo elemento de A está contenido en B.

-   Denotaremos el conjunto unión de ***A, B*** como $A \cup B$ de tal forma que contiene a todos los elementos de **A o B**

-   Denotaremos el conjunto unión de ***A, B*** como $A \cap B$ de tal forma que contiene a todos los elementos de **A y B**

-   Denotaremos al conjunto complemento de **A** como $A^c$ de tal forma que contiene a todos los elementos que están en $\Omega$, pero no en **A.**

-   Definimos la resta de conjuntos $A-B$ como el conjunto que contiene a todos los elemento que están en A, pero no de B, es decir, $A \cap B^c$.

## Axiomas

Dos eventos A y B son mutuamente excluyentes o disjuntos si ambos no comparten elementos o resultados, es decir $A \cap B = \emptyset$.

*Experimento Aleatorio:* Cantidad de homicidios diarios en el país.

**A** = No hay homicidios. = $\{0\}$

**B** = Hay 2 homicidios o más. = $\{2,3,4,\cdots\}$

$A\cap B = \emptyset$

$\therefore \text{A y B son mutuamente excluyentes}$

## Axiomas

#### **Definición (Conjunto Potencia)**

El conjunto potencia de A es la colección de subconjuntos de A usualmente denotado por $\mathcal{P}(A)$

$a \in \mathcal{P}(A) \quad \text{si} \quad a\subset A$

Ejemplo:

Sea $A = \{1,2,3\}$

Entonces $\mathcal{P}(A) = \{\emptyset, \{1\}, \{2\}, \{3\}, \{1,2\}, \{1,3\}, \{2,3\}, \{1,2,3\} \}$

Note que si el conjunto A tiene n elemento el conjunto $\mathcal{P}(A)$ tiene $2^n$ elementos.

## Axiomas (para eventos)

Sea $\mathcal{P}(\Omega)$ el conjunto potencia del espacio muestral, y sea $\mathcal{A}\subseteq \mathcal{P}(\Omega)$. Se dice que $\mathcal{A}$ es una $\sigma-\text{álgebra en }\Omega$ si cumple con los axiomas:

-   **Axioma 1:** $\Omega \in \mathcal{A}$

-   **Axioma 2:** $\text{Si } A\in \mathcal{A},\text{entonces, } A^c \in \mathcal{A}$

-   **Axioma 3:** $\text{Si } A_1, A_2, \dots\in \mathcal{A},\text{entonces, } \bigcup_{i=1}^{\infty} A_i \in \mathcal{A}.$

#### **Definición (Espacio Medible)**

A la dupla $(\Omega, \mathcal{A})$ se le llama espacio medidible si $\Omega \ne \emptyset$ y $\mathcal{A}$ es una $\sigma-\text{álgebra en }\Omega.$

## Axiomas (para probabilidades)

Sea $\mathcal{A}$ una $\sigma-\text{álgebra en }\Omega.$ Se define una probabilidad, o lo que es equivalente, una medida de probabilida sobre $\Omega$, a la función:

$$
P: \mathcal{A} \rightarrow \mathbb{R}
$$

la cual cumple con los axiomas de Kolmorov:

-   **Axioma 4:** $P(A) \geq 0, \forall A \in \mathcal{A}.$

-   **Axioma 5:** $P(\Omega) = 1.$

-   **Axioma 6:** $\text{Para cada sucesión de eventos } A_1, A_2, \dots \in \mathcal{A}, \text{ disyuntos dos a dos, se cumple que:}$

$$ P \left( \bigcup_{i=1}^{\infty} A_i \right) = \sum_{i=1}^{\infty} P(A_i) $$

La cual corresponde a una serie convergente (debido al axioma 5).

## Axiomas (Propiedades de las medidas de probabilidad)

#### **1)** $P(\emptyset) = 0.$

**Prueba:** Considere que $\Omega = \Omega \cup \emptyset$

$1=P(\Omega) = P(\Omega \cup \emptyset) = P(\Omega)+P(\emptyset) = 1 +P(\emptyset) \Rightarrow P(\emptyset) =0$

#### **2)** Si $A \cap B = \emptyset$ es cualquier evento, entonces: $P(A \cup B) = P(A) + P(B).$

**Prueba:** Usando el axioma 6 y tomando $A_1 = A$ y $A_2 = B$ .

#### **3)** Si $A$ es cualquier evento, entonces: $P(A^c) = 1- P(A).$

**Prueba:** Considere que $\Omega = A \cup A^c,$ los cuales son eventos mutamentes disjuntos. Entonces:

$1=P(\Omega) = P(A \cup A^c) = P(A)+P(A^c)$

$P(A^c) =1-P(A)$

## Axiomas (Propiedades de las medidas de probabilidad)

#### 4) Si $A$ y $B$ son eventos, entonces: $P(B-A) = P(A\cap B^c) = P(A) - P(A\cap B).$

**Prueba:** Ejercicio Note que $\small A=(A\cap B^c) \cup (A\cap B)$

#### **5)** Si $A$ y $B$ son eventos tales que, $A\subseteq B$, entonces: $P(B-A) = P(B) - P(A).$

**Prueba:** Ejercicio. Sugerencia: si $A\subseteq B,$ entonces $B=A\cup(A^c \cap B)$

#### **6)** Si $A$ y $B$ son eventos tales que, $A\subseteq B$, entonces: $P(A) \leq P(B)$

**Prueba:** Ejercicio.

## Axiomas

#### **Definición**

A la terna $(\Omega, \mathcal{A}, P),$ donde $\mathcal{A}$ es una $\sigma-\text{álgebra sobre }\Omega, \text{ y P}$ es una medida de probabilidad, se le llama espacio de probabilidad. Si $A\in\mathcal{A},$ al valor $P(A)$ se le llama la probabilidad de A.

#### **Definición**

Sea $\Omega$ un conjunto finito no vacío. La función de probabilidad:

$$
P(X)=\frac{\mid A \mid}{\mid \Omega \mid}
$$

definida por $P: \mathcal{P}(\Omega) \rightarrow \mathbb{R}^+\cup\{0\},$ se conoce como ***Ley de Laplace.***

## Ley Aditiva de la Probabilidad

Para A y B eventos cualesquiera se cumple que:

$$
\small P(A\cup B) = P(A) + P(B) - P(A\cap B)
$$

Prueba:

Considere que $\small A\cup B = (A\cap B^c) \cup (B\cap A^c) \cup (A\cap B)$

$\small \Rightarrow P(A\cup B ) = P(A\cap B^c) + P(B\cap A^c) + P(A\cap B), \quad \text{Suma de probabilidad de eventos disjuntos}$

Note que $\small A=(A\cap B^c) \cup (A\cap B)$ y $B=(A^c\cap B) \cup (A\cap B)$

$\small P(A)= P(A\cap B^c) + P(A\cap B), \quad \text{Suma de probabilidad de eventos disjuntos}$

$\small P(B)= P(A^c\cap B) + P(A\cap B),\quad \text{Suma de probabilidad de eventos disjuntos}$

$\small \Rightarrow P(A)+P(B) = P(A\cap B^c) +P(A^c\cap B)+ 2\cdot P(A\cap B)$

$\small \Rightarrow P(A)+P(B) = P(A\cup B) + P(A\cap B)$

$\small \Rightarrow P(A\cup B) = P(A)+P(B)-P(A\cap B)$

## Axiomas

**Teorema:** Para $A_1, A_2, \cdots, A_n$ eventos cualesquiera, se tiene que:

$P(A_1 \cup A_2 \cdots \cup A_n)$

$=\sum_{i=1}^n P(A_i)- \sum_{i<j} P(A_i \cap A_j)+ \sum_{i<j<k} P(A_i \cap A_j \cap A_k)- \dots$

$\cdots+ (-1)^{n+1} P(A_1 \cap A_2 \cap \dots \cap A_n)$
