---
title: "Introducción^1^"
subtitle: " [XS-0122 Modelos Probabilísticos II Semestre 2025](https://christopher-tr.github.io/XS3310-I25)"
format: clean-revealjs
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Christopher Torres Rojas
    url: https://christopher-tr.github.io/
    email: christopher.torres@ucr.ac.cr
    affiliations: 
    - name: Escuela de Estadística, Universidad de Costa Rica
      url: https://www.estadistica.ucr.ac.cr/
#date: last-modified
lang: es  # español
---

## Aspectos importantes

-   **Información importante**

    1.  [Mediación Virtual](https://mv1.mediacionvirtual.ucr.ac.cr/course/view.php?id=39199)
    2.  [Programa del curso](https://shuwei325.github.io/XS3310-I25/Programa-XS3310.pdf)
    3.  [Llenar el formulario (pendiente)](https://forms.gle/6r7XSi5EwSYdrk8D6)
    4.  [Slack](https://join.slack.com/t/teora-i25/shared_invite/zt-31gwglhsw-5lBmkz6AAndLf4kCgQIfsg)

-   **Reglamentación**

    -   [El Reglamento de Régimen Académico Estudiantil](https://www.cu.ucr.ac.cr/normativ/regimen_academico_estudiantil.pdf)
    -   [El Reglamento de Orden y Disciplina de los Estudiantes](https://www.cu.ucr.ac.cr/normativ/orden_y_disciplina.pdf)
    -   [El Reglamento de la Universidad de Costa Rica contra el Hostigamiento Sexual](https://www.cu.ucr.ac.cr/normativ/hostigamiento_sexual.pdf)
        -   [Comisión Institucional Contra el Hostigamiento Sexual](https://hostigamientosexualucr.ucr.ac.cr/)
            -   [Acerca de...](https://www.ucr.ac.cr/comision-institucional-contra-el-hostigamiento-sexual.html)
            -   [Video](https://www.youtube.com/watch?v=OiUyqC8qrnI)

# Qué vamos a ver en los cursos teóricos de la carrera:

¿Temas que se abarcarán en modelos probabilísticos I y II?

<https://seeing-theory.brown.edu>

<https://www.acsu.buffalo.edu/~adamcunn/probability/probability.html>

# Motivación

¿Por qué es necesario conocer de teoría de probabilidad?

## Conceptos que abarcaremos en este curso.

-   Probabilidad

-   Espacio Muestral

-   Análisis Combinatorio <br> <br>

-   Variable aleatoria (v.a.)

-   Esperanza E(X)

-   Varianza Var(X)

-   Distribuciones Discretas

-   Distribuciones Continuas <br> <br>

-   Versomilitud

-   Momentos Poblacionales

-   Desigualdad de Markok

-   Teorema de Chebyshev <br> <br>

## Probabilidad

¿Qué se entiende por probabilidad?

De manera intuitiva, la probabilidad puede entenderse como una medida cuantitativa que nos dice que tan favorable es la ocurrencia de un suceso o evento.

Pero a esta definición le falta rigor matemático.

## Definiciones

**Experimento Aleatorio:** Es un fenomeno que se puede repetir en condiciones similares, no se puede predecir el resultado del experimeto previamente.

**Espacio Muestral** $\Omega$ **:** Conjunto de todos los posibles resultados.

**Evento:** Es cualquier acontecimiento que pueda ocurrir. <br> <br>

**Ejemplo:**

*Experimento Aleatorio:* Lanzar un dado.

*Espacio Muestral* $\Omega = \{1,2,3,4,5,6\}$

*Evento A:* Que salga un número par = $\{2,4,6\}$

*Evento B:* Que salga un 5 = $\{5\}$

*Evento C:* Que salga un número mayor a 10 = $\emptyset$

## Enfoques de la Probabilidad

1.  **Enfoque Clásico.**

2.  **Enfoque Frecuentista.**

3.  **Enfoque Subjetivo.**

4.  **Enfoque Axiomático.**

## Enfoques Clásico

Supuestos:

-   Espacio muestral finito.

-   Variable Aleatoria discreta.

-   Resultados son mutuamente excluyentes e igualmente probables.

$$
P(A) = \frac{\text{Casos Favorables}}{\text{Casos Totales}} = \frac{\text{Cardinalidad de A}}{\text{Cardinalidad de }\Omega} = \frac{n(A)}{n}
$$

Ejemplo:

Obtener una cara al lanzar una moneda equilibrada $P(A) = \frac{\mid \{Cara\}\mid}{\mid\{Cara,  Escudo \}\mid} = \frac{1}{2}$

La suma de dos dados al lanzarlos sea 3 $P(A) = \text{?}$

## Limitaciones

-   Número de casos favorables desconocido.

-   Total de resultados podría ser infinito.

-   Resultados no igualmente probables, ejemplo: una moneda cargada que favorezca la aparición de escudo.

## Enfoques Frecuentista

También conocido como enfoque *a posteriori*. Se basa en resultados empíricos, y se interpreta como la frecuencia relativa de un evento.\
\
Es decir si se tienen ***n*** repeticiones de un experimento y un evento ***A*** ocurre ***n(A)*** veces entonces la probabilidad de ocurrencia del evento queda dada por la frecuencia relativa de **A** :

$$
f(A) = \frac{n(A)}{n}
$$

Si las repeticiones se realizan de manera similar bajo las mismas condiciones y n es suficientemente grande entonces:

$$
\lim_{n \to \infty} \frac{n(A)}{n} = P(A)
$$

## Limitaciones

-   Dependencia de la cantidad de repeticiones ***"n"***.

-   Repetición del experimento en condiciones similares.

-   No convergencia de las frecuencias relativas.

## Enfoques

### **Enfoque Subjetivo:**

Es una medida de creencia personal de un evento. Lo cual presenta problemas ya que dos personas pueden asignar probabilidades distintas, es útil cuando no se tiene conocimiento del evento.

### **Enfoque Axiomativo - Enfoque de Kolmogorov.**

Está apoyado en la teoría de conjuntos y evita las limitaciones de los enfoques clásicos, frecuentista y subjetivo.

Como su nombre lo indica se basa en la definición de axiomas para la construcción de la teoría de probabilidad.

## Repaso Teoría de Conjuntos

-   En **teoría de conjuntos** se denota como $S$ al conjunto de todos los elementos.

-   Diremos que ***A es subconjunto de B*** $\left( A \subset B\right)$. Si todo elemento de A está contenido en B.

-   Denotaremos el conjunto unión de ***A, B*** como $A \cup B$ de tal forma que contiene a todos los elementos de **A o B**

-   Denotaremos el conjunto unión de ***A, B*** como $A \cap B$ de tal forma que contiene a todos los elementos de **A y B**

-   Denotaremos al conjunto complemento de A como $A^c$ de tal forma que contiene a todos los elementos que están en $S$, pero no en A.

-   Definimos la resta de conjuntos $A-B$ como el conjunto que contiene a todos los elemento que están en A, pero no de B, es decir, $A \cap B^c$.

## Ejemplos

**Ejemplo 1:** Supongamos que vamos a lanzar un dado. Entonces podríamos definir:

$S = \{1,2,3,4,5,6\}$

$A = \text{obtener un número par}$

$B = \text{obtener un número primo}$

Defina: $A,B, A\cup B, A^c, B^c, A\cap B, A^c-B, A^c-B^c, A\cup (B \cap A^c)$

## Ejemplos

**Ejemplo 2:** Supongamos que estamos midiendo la proporción de foráneos que tienen clases en la facultad de ciencias económicas el día de hoy. Sea:

$S = \{ p \in \mathbb{R} \mid 0 \leq p \leq 1 \}$

$A = \text{El día de hoy hay más foraneos que residentes }$

$B = \text{Al menos el 20% de los estudiantes el día de hoy son foráneos }$

Defina: $A,B, A\cup B, A^c, B^c, A\cap B, A^c-B, A^c-B^c, A\cup (B \cap A^c)$

## Repaso Teoría de Conjuntos

Propiedades: Sean ***A,B,C*** tres conjuntos cualesquiera.

-   $A\cup A^c = S$

-   $A \cap A^c = \emptyset$

-   $A \cap  \emptyset =  \emptyset$

-   $A \cup  \emptyset = A$

-   $A \cap  S =  A$

-   $A \cup  S =  S$

-   $A \cap(B\cup C) = (A\cap B)\cup (A \cap C)$ "Leyes Distributivas"

-   $A \cup(B\cap C) = (A\cup B)\cap (A \cup C)$ "Leyes Distributivas"

-   $(A\cap B)^c = A^c \cup B^c$ "Leyes de Morgan"

-   $(A\cup B)^c = A^c \cap B^c$ "Leyes de Morgan"

-   Si **A y B** son mutuamente excluyentes entonces $A\cap B = \emptyset$.

## Ejercicios

Demuestre que:

**a)** $A = (A \cap B) \cup (A \cap \overline{B})$

**b)** Si $B \subseteq A$ entonces $A = B \cup (A \cap \overline{B})$

**c)** Además demuestre que $(A \cap B) \text{ y } (A \cap \overline{B})$ son mutuamentes excluyentes y que, por tanto, $A$ es la unición de dos conjuntos mutuamentes excluyentes.

## Próximamente

### Consecuencia de la definición clásica:

1.  $0 \leq P(A) \leq 1$

2.  $P(A \cup B)= P(A)+P(B) - P(A\cap B)$

3.  $P(A^c)=1-P(A)$

4.  $P(\emptyset)=0$

5.  $P(\Omega)=1$
